name: Build a project with Qt6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:        
  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.6.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        cache: 'true'
        archives: 'qtdeclarative qtbase icu'
    
    - name: Build All
      run: cmake -B ${{github.workspace}}/build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
