name: Build a project with Qt6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:        
  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.6.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        cache: 'true'
        archives: 'qtdeclarative qtbase icu'
    
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml5-contextproperty -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml5-contextproperty/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml5-contextproperty --config ${{env.BUILD_TYPE}}
    
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml5-singletoninstance -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml5-singletoninstance/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml5-singletoninstance --config ${{env.BUILD_TYPE}}
    
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml5-singletontype -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml5-singletontype/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml5-singletontype --config ${{env.BUILD_TYPE}}
    
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml6-pragmasingleton -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml6-pragmasingleton/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml6-pragmasingleton --config ${{env.BUILD_TYPE}}
    
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml6-qmlelement -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml6-qmlelement/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml6-qmlelement --config ${{env.BUILD_TYPE}}
   
    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml6-singleton -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml6-singleton/

    - name: Build
      run: cmake --build ${{github.workspace}}/build/qml6-singleton --config ${{env.BUILD_TYPE}}

    - name: Configure
      run: cmake -B ${{github.workspace}}/build/qml6-subdirectories -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S qml6-subdirectories/

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
